excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - SSSOrder/Controllers/OrderController.swift
# implicitly
line_length: 220

# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
