# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SSSOrder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSSOrder
  pod 'SwiftLint'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Kingfisher', '~> 3.0'
  pod 'HMSegmentedControl'
  pod 'FSCalendar'
  pod 'Moya/RxSwift'
  pod 'Alamofire', '~> 4.4'
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'

  target 'SSSOrderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
  end

end
