# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SSSOrder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSSOrder
  pod 'SwiftLint'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Kingfisher', '~> 3.0'
  pod 'DateToolsSwift'
  pod 'HMSegmentedControl'
  pod 'FSCalendar'
  pod 'Moya'
  pod 'Alamofire', '~> 4.4'
  pod 'ReachabilitySwift', '~> 3'
  pod 'Whisper'

  target 'SSSOrderTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
